from .user import UserSerializer
from .branch import BranchSerializer
from .classroom import ClassroomSerializer
from .course import CourseSerializer
from .course_category import CourseCategorySerializer
from .facility import  FacilitySerializer
from .instructor import InstructorSerializer
from .vehicle import VehicleSerializer
from .student import StudentSerializer
from .enrollment import EnrollmentSerializer
from .session import SessionSerializer
