# Generated by Django 5.1.1 on 2024-10-07 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_facility_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('MT', 'Manual Transmission'), ('AT', 'Automatic Transmission')], default='MT', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.date(2024, 10, 7)),
        ),
    ]
