# Generated by Django 5.1.1 on 2024-10-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
