# Generated by Django 5.1.1 on 2024-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_session_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
    ]
