# Generated by Django 5.1.1 on 2024-10-16 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.date(2024, 10, 16)),
        ),
    ]
