# Generated by Django 5.1.1 on 2024-11-11 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Archived', 'Archived')], default='Available', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Archived', 'Archived')], default='Open', max_length=8),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.date(2024, 11, 11)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Awaiting Action', 'Awaiting Action'), ('Awaiting Follow-Up', 'Awaiting Follow-Up'), ('All Sessions Scheduled', 'All Sessions Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Forfeited', 'Forfeited'), ('Archived', 'Archived')], default='Awaiting Action', max_length=30),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled'), ('Archived', 'Archived')], default='Scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Archived', 'Archived')], default='Available', max_length=12),
        ),
    ]
