# Generated by Django 5.1.1 on 2024-11-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='year_started',
        ),
    ]
