# Generated by Django 5.1.1 on 2024-11-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_instructor_year_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='year_acquired',
        ),
    ]
