# Generated by Django 5.1.1 on 2024-12-11 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_enrollment_enrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine phone number (e.g., +63917xxxxxxx or 0917xxxxxxx).', regex='^(?:\\+63|0)\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine phone number (e.g., +63917xxxxxxx or 0917xxxxxxx).', regex='^(?:\\+63|0)\\d{9}$')]),
        ),
    ]
